name: lantern-xgb
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alembic=1.16.4=py313h06a4308_0
  - autograd=1.8.0=pyhd8ed1ab_0
  - autograd-gamma=0.5.0=pyhd8ed1ab_1
  - beautifulsoup4=4.13.5=py313h06a4308_0
  - blas=1.0=openblas
  - boruta_py=0.3=pyhd8ed1ab_1
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotlicffi=1.0.9.2=py313h6a678d5_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - certifi=2025.10.5=py313h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cloudpickle=3.1.1=py313h06a4308_0
  - colorlog=6.9.0=pyh707e725_1
  - contourpy=1.3.3=py313h7037e92_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=h1110e0f_3
  - ecos=2.0.14=py313hf0014fa_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.59.2=py313h3dea7bd_0
  - formulaic=1.2.0=py313h78bf25f_2
  - freetype=2.13.3=h4a9f257_0
  - greenlet=3.1.1=py313h6a678d5_0
  - gseapy=0.9.5=py_1
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - imbalanced-learn=0.14.0=pyhd8ed1ab_0
  - interface_meta=1.3.0=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.9=py313hc8edb43_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.15.0=hc1efc7f_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=15.1.0=hcea5267_4
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.29=ha39b09d_0
  - libosqp=0.6.3=h6a678d5_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libqdldl=0.1.7=h6a678d5_0
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hecacb30_2
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxgboost=3.0.4=cpu_h2ebb00f_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - lifelines=0.30.0=pyhd8ed1ab_1
  - llvmlite=0.44.0=py313hc1e8f15_1
  - lmdb=0.9.31=hb25bd0a_0
  - lxml=5.3.0=py313h57af460_1
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.2.3=py313h06a4308_0
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib=3.10.5=py313h06a4308_0
  - matplotlib-base=3.10.5=py313he37261f_0
  - mesalib=25.1.5=h31e3550_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql=8.4.0=h721767e_2
  - narwhals=2.3.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - numba=0.61.2=py313h6a678d5_0
  - numexpr=2.11.0=py313ha5a4a6c_1
  - openjpeg=2.4.0=h9ca470c_2
  - openldap=2.6.10=he9288cc_1
  - openssl=3.5.2=h26f9b46_0
  - optuna=4.5.0=pyhd8ed1ab_0
  - osqp=0.6.7.post3=py313ha87cce1_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py313h280b501_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.4.0=py313h5eee18b_0
  - pip=25.2=pyh145f28c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py-xgboost=3.0.4=cpu_pyh718b53a_0
  - pyaml=25.5.0=py313h06a4308_0
  - pycparser=2.23=py313h06a4308_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=6.7.1=py313h8dad735_2
  - pyqt6-sip=13.9.1=py313h6ce4db3_2
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.5=h4612cfd_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyyaml=6.0.2=py313h5eee18b_0
  - qdldl-python=0.1.7.post5=np2py313h4a602f7_1
  - qhull=2020.2=h4bd325d_2
  - qtbase=6.7.3=h10a5587_4
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=py313h06a4308_0
  - scikit-learn=1.7.1=py313h06d4379_0
  - scikit-optimize=0.10.2=pyhd8ed1ab_1
  - scikit-survival=0.25.0=np2py313h41bc45f_0
  - scipy=1.16.0=py313hcb7a30d_1
  - seaborn=0.13.2=py313h06a4308_3
  - setuptools=72.1.0=py313h06a4308_0
  - shap=0.47.2=py313hdc9ef3c_0
  - sip=6.10.0=py313h6a678d5_0
  - six=1.17.0=py313h06a4308_0
  - slicer=0.0.8=py313he08a061_1
  - soupsieve=2.5=py313h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlalchemy=2.0.43=py313h7e39e78_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=py313h7040dfc_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=py313h06a4308_0
  - webencodings=0.5.1=py313h06a4308_2
  - wrapt=1.17.3=py313h07c4f96_1
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - asttokens==3.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - borutashap==1.0.17
      - cachetools==6.2.4
      - category-encoders==2.8.1
      - cffi==2.0.0
      - click==8.3.1
      - comm==0.2.3
      - cryptography==46.0.3
      - databricks-sdk==0.77.0
      - decorator==5.2.1
      - docker==7.1.0
      - einops==0.7.0
      - executing==2.2.1
      - fastapi==0.128.0
      - filelock==3.20.0
      - flask==3.1.2
      - flask-cors==6.0.2
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.47.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - grpcio==1.76.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - huey==2.6.0
      - importlib-metadata==8.7.1
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyterlab-widgets==3.0.15
      - lazypredict==0.2.16
      - lightgbm==3.3.5
      - lightning-utilities==0.15.2
      - markdown==3.9
      - markdown-it-py==4.0.0
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mlflow==3.8.1
      - mlflow-skinny==3.8.1
      - mlflow-tracing==3.8.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.5
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opentelemetry-api==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - optuna-integration==4.5.0
      - ordinalgbt==0.1.2
      - parso==0.8.5
      - patsy==1.0.1
      - pexpect==4.9.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pynomo==0.3.6
      - pytest-runner==6.0.1
      - python-dotenv==1.2.1
      - pytorch-lightning==2.4.0
      - pytorch-tabnet==4.1.0
      - pytorch-tabular==1.1.1
      - rich==14.2.0
      - rsa==4.9.1
      - smmap==5.0.2
      - sqlparse==0.5.5
      - stack-data==0.6.3
      - starlette==0.50.0
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.9.0
      - torchmetrics==1.5.2
      - traitlets==5.14.3
      - triton==3.5.0
      - typing-inspection==0.4.2
      - uvicorn==0.40.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wheel==0.45.1
      - widgetsnbextension==4.0.14
      - xgboost-cpu==3.0.4
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/ddalfovo/miniconda3/envs/xgb
